### ISSUE TITLE
Alignment of files in the repository

### ISSUE THREAD

**Issue by Yaswanth14** [AshuKulu/HacktoberFest2021#481]
**Some of the files are not placed in their respective domain.**
 For example Area.c is not present in the c folder

**Comment by Yaswanth14** [comment]
Hey there! I'm a newbie and looking for good practices. Can I know if this is the right way to request for making changes? 
and also I want to resolve this issue ( #481 ), can I?

**Comment by Palaksharma23** [comment]
Hii Can i take up this issue ?

**Comment by AshuKulu** [comment]
Yes you can
