### ISSUE TITLE
Created Solution for Merge sort in Py

### ISSUE THREAD

**Issue by flick-23** [AshuKulu/HacktoberFest2021#829]

**Comment by flick-23** [comment]
https://github.com/AshuKulu/HacktoberFest2021/pull/828

**Comment by danielskjo** [comment]
Can I be assigned this?

**Comment by Smita543** [comment]
i would love to write merge sort code in python.

**Comment by flick-23** [comment]
I have already provided the solution :)

**Comment by Smita543** [comment]
Okay 🙂
